# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f0ed93a8ecbd7b22f177a74db131c78f02c7d5c1f32e9ac0dae341f03771c147c893a945a217f854349f881bd43dee80dcf7566ac1e6e726bc0d0df7603f6f3

test:
  secret_key_base: 0790687bf1d4be6dd2cf147c095a3ea413e8240d03cf1de992ff5e4dd0af37a8b2fe27515a744348d73323d7d57f7b24091edb46f3e423c70ba996c48bdc6afd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
